flags:
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/robstewart57/rdf4h.git
    commit: 89d7c9eeabf0fdb4124f2cecfb725b88c2acb1d9
- location:
    git: https://github.com/robstewart57/hsparql.git
    commit: 9c00c51660e4dca0c4d35f4d4400d78512b8e94a
extra-deps:
- hgal-2.0.0.2
resolver: lts-6.11

